version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5072:8080"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "server=db;port=3306;database=task_team_db;user=root;password=task1team2db;"

  db:
    image: mysql:8.0
    container_name: mysql-task-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: task1team2db
      MYSQL_DATABASE: task_team_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
